### ISSUE TITLE
Audio Bitrate & Audio Formats

### ISSUE THREAD

**Issue by galopeynet** [maythamfahmi/YouTuber#26]
audio best source like youtube-dl -f, 140 m4a audio-only tiny 129k, m4a_dash container. **(https://index.teststrana.com/img/ytdsugest.jpg)**
Export to m4a format? And the last suggestion is whether the FFmpeg path can be used on windows.
Is it possible?  :)

**Comment by maythamfahmi** [comment]
I will look at it when soon posible, thanks for input.

**Comment by maythamfahmi** [comment]
@galopeynet  check this release https://github.com/maythamfahmi/YouTuber/releases/tag/v2.5.6 

just add -a:m4a and you will get m4a in stead of default mp3

**Comment by galopeynet** [comment]
Thx Man

sri, 23. velj 2022. 22:13 Maytham Fahmi ***@***.***> je
napisao:

**Comment by galopeynet** [comment]
Great works , but I still get Bit rate 96kbps by default, no option for the best audio?had hope for it :)  Poslano iz programa Pošta za Windows Pošiljatelj: Maytham FahmiPoslano:23. veljače 2022. 22:13Primatelj: maythamfahmi/YouTuberKopija: galo; MentionPredmet: Re: [maythamfahmi/YouTuber] Audio Bitrate & Audio Formats (Issue ***@***.*** check this release https://github.com/maythamfahmi/YouTuber/releases/tag/v2.5.6just add -a:m4a and you will get m4a in stead of default mp3—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>
