### ISSUE TITLE
video is null error

### ISSUE THREAD

**Issue by grafinery** [maythamfahmi/YouTuber#48]
It downloads some videos but It says "**1- video is null**" for some videos (ie. https://www.youtube.com/watch?v=4r454dad7tc )
I tried your binary 3.5.6 and also compile the source code without any error. Results are same.

**To Reproduce**
download.txt:
https://www.youtube.com/watch?v=4r454dad7tc

**command:**
downloadyoutube -l download.txt
or
downloadyoutube -l https://www.youtube.com/watch?v=4r454dad7tc

**result:**
\1- video is null

My OS: Win10/x64

**Comment by maythamfahmi** [comment]
Thank you for reaching out, I have made fix for this issue. It is caused, of uploaded video or sound files with out extension.

I will merge this fix to and deploy a new version.

**Comment by maythamfahmi** [comment]
This issue solved by release [3.6.1](https://github.com/maythamfahmi/YouTuber/releases/tag/3.6.1)
